/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:3c1f68f5-cd05-4ffc-b0e4-4be2cbb76d18",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_GLnF5zvMb",
    "aws_user_pools_web_client_id": "7lboq07uapk3gochgbr35ak34",
    "oauth": {}
};


export default awsmobile;
